// The house material atlas: one 2048² texture, one draw call, real brick.
//
// assets/materials/atlas.png + atlas.json are generated by tools/make_atlas.py.
// The atlas holds two kinds of cell:
//
//   tiled: true   brick / stone / siding / clapboard / stucco / shingle / cedar.
//                 UVs are in REPEATS, not in [0,1]: the shader wraps them inside
//                 the cell (uv = rect.xy + fract(uvLocal) * rect.zw), so a 6 m
//                 wall of brick (metres 0.6) is simply u 0 -> 10.
//   tiled: false  decals — windows, doors, garage doors, porch rails. UVs are
//                 absolute atlas coordinates, no wrapping, and the alpha channel
//                 cuts the silhouette (the shader discards alpha < 0.35).
//
// 'flat' is a plain white tile at the atlas origin, so a vertex left at UV (0,0)
// samples white. Because the shader MULTIPLIES the texture into the vertex
// colour, untextured vertex-coloured geometry (roads, ground, trees) can sit in
// the same chunk mesh as textured houses and come out unchanged — one draw for
// the whole chunk. That is also why tinting works: vinyl_white × tint = siding
// in any colour you like.
//
// Usage
//   const mats = await loadMaterials(renderer);
//   mats.quadTex(mb, bl, br, tr, tl, 'brick_red', { tint: rgb(0xffffff) });
//   ...
//   renderer.draw(mesh, model, { tex: mats.tex });
//
// Hand-rolled geometry that is not a quad uses the stateful form:
//   const q = mats.wallUV(mb, 'vinyl_blue', wallW, wallH);  // sets mb.curRect
//   mb.vert(x, y, z, nx, ny, nz, tint, q.u0, q.v1);         // ... more verts
//   mats.end(mb);                                           // clears mb.curRect
// Forgetting end() means the NEXT vertices keep tiling that material — always
// close a textured run.

export const ATLAS_DIR = 'assets/materials/';
export const WHITE = [1, 1, 1];

let current = null;   // last atlas loaded; backs the bare helpers at the bottom

function loadImage(url) {
  return new Promise((res, rej) => {
    const im = new Image();
    im.onload = () => res(im);
    im.onerror = () => rej(new Error('cannot load ' + url));
    im.src = url;
  });
}

/**
 * Load atlas.png + atlas.json and upload the texture.
 *
 * @param {object} renderer  a core/gl.js Renderer (only .texture() is used)
 * @param {object} [opts]
 *   base      directory holding atlas.png / atlas.json (default ATLAS_DIR)
 *   manifest  pre-parsed manifest (skips the fetch — used by the node smoke test)
 *   image     pre-loaded image (skips the fetch)
 *   aniso     anisotropy to request (default 16, clamped to the driver's max)
 *   current   set this atlas as the module default (default true)
 * @returns {Promise<Materials>}
 */
export async function loadMaterials(renderer, opts = {}) {
  const base = opts.base || ATLAS_DIR;
  const manifest = opts.manifest
    || await fetch(base + 'atlas.json').then((r) => {
      if (!r.ok) throw new Error('cannot load ' + base + 'atlas.json');
      return r.json();
    });
  let tex = null;
  if (renderer && renderer.texture) {
    const image = opts.image || await loadImage(base + 'atlas.png');
    tex = renderer.texture(image, { aniso: opts.aniso === undefined ? 16 : opts.aniso });
  }
  const mats = new Materials(manifest, tex);
  if (opts.current !== false) current = mats;
  return mats;
}

export class Materials {
  constructor(manifest, tex) {
    this.size = manifest.size;
    this.tex = tex;
    this.tiles = manifest.tiles;
    this.list = Object.keys(manifest.tiles);
    this._rect = new Map();
    for (const name of this.list) {
      const t = this.tiles[name];
      this._rect.set(name, [t.u0, t.v0, t.u1 - t.u0, t.v1 - t.v0]);
    }
    if (!this.tiles.flat) throw new Error("atlas has no 'flat' tile");
  }

  has(name) { return Object.prototype.hasOwnProperty.call(this.tiles, name); }

  /** Manifest entry: { u0, v0, u1, v1, metres, tiled, aspect }. Throws if unknown. */
  uv(name) {
    const t = this.tiles[name];
    if (!t) throw new Error('unknown material "' + name + '"');
    return t;
  }

  /** [u0, v0, du, dv] — what goes in MeshBuilder.curRect. Do not mutate. */
  rect(name) { this.uv(name); return this._rect.get(name); }

  /** Metres covered by one repeat (tiled) / natural width in metres (decal). */
  metres(name) { return this.uv(name).metres; }

  /** Natural decal size in metres, scaled: { w, h }. */
  decalSize(name, scale = 1) {
    const t = this.uv(name);
    const w = t.metres * scale;
    return { w, h: w * (t.aspect === undefined ? 1 : t.aspect) };
  }

  /** Stop tiling: later vertices sample the UV they are given, as-is. */
  end(mb) { mb.curRect = null; return this; }

  /**
   * UV corners for a widthM × heightM surface of material `name`, and — the
   * stateful half — sets mb.curRect so the vertices emitted next tile inside
   * that atlas cell. Returns { u0, u1, v0, v1, rect, tiled, repeatU, repeatV }
   * where u0/v0 is the TOP-LEFT corner and u1/v1 the BOTTOM-RIGHT, in the units
   * the shader wants (repeats for tiled cells, absolute UV for decals).
   *
   * The bottom edge lands on a whole tile boundary and the partial repeat ends
   * up at the top — the way real siding is hung.
   *
   * opts: tint is ignored here (that is a vertex colour); uOffset / vOffset
   * shift the pattern (per-house jitter so neighbours do not line up);
   * metres overrides the tile's repeat size; repeatU / repeatV set the repeat
   * count outright.
   */
  wallUV(mb, name, widthM, heightM, opts = {}) {
    const t = this.uv(name);
    const rect = this.rect(name);
    mb.textured = true;
    if (!t.tiled) {
      mb.curRect = null;
      return {
        rect, tiled: false, repeatU: 1, repeatV: 1,
        u0: t.u0, v0: t.v0, u1: t.u1, v1: t.v1,
      };
    }
    const m = opts.metres || t.metres;
    const ru = opts.repeatU === undefined ? widthM / m : opts.repeatU;
    const rv = opts.repeatV === undefined ? heightM / m : opts.repeatV;
    const u0 = opts.uOffset || 0;
    const v1 = 1 + (opts.vOffset || 0);
    mb.curRect = rect;
    return { rect, tiled: true, repeatU: ru, repeatV: rv, u0, u1: u0 + ru, v0: v1 - rv, v1 };
  }

  /**
   * Emit one textured quad. Corners go bottom-left, bottom-right, top-right,
   * top-left (counter-clockwise seen from the front, same winding as
   * MeshBuilder.quad). Width and height in metres are taken from the corner
   * distances unless opts.widthM / opts.heightM say otherwise.
   *
   * opts: tint (vertex colour, default white — the texture multiplies it),
   *       n (normal override), plus everything wallUV accepts.
   * Returns the index of the first vertex.
   */
  quadTex(mb, p0, p1, p2, p3, name, opts = {}) {
    const w = opts.widthM === undefined ? dist(p0, p1) : opts.widthM;
    const h = opts.heightM === undefined ? dist(p0, p3) : opts.heightM;
    const q = this.wallUV(mb, name, w, h, opts);
    const c = opts.tint || WHITE;
    const n = opts.n || faceNormal(p0, p1, p2);
    const b = mb.vert(p0[0], p0[1], p0[2], n[0], n[1], n[2], c, q.u0, q.v1);
    mb.vert(p1[0], p1[1], p1[2], n[0], n[1], n[2], c, q.u1, q.v1);
    mb.vert(p2[0], p2[1], p2[2], n[0], n[1], n[2], c, q.u1, q.v0);
    mb.vert(p3[0], p3[1], p3[2], n[0], n[1], n[2], c, q.u0, q.v0);
    mb.tri(b, b + 1, b + 2);
    mb.tri(b, b + 2, b + 3);
    if (!opts.keepRect) mb.curRect = null;
    return b;
  }

  /**
   * Emit a convex polygon (gable end, dormer cheek, roof triangle) textured with
   * `name`. UVs come from projecting each point onto a frame: opts.origin +
   * opts.uAxis / opts.vAxis (unit vectors in metres). Without a frame the first
   * edge becomes +u and the face normal × that becomes -v, i.e. "up the wall".
   */
  faceTex(mb, pts, name, opts = {}) {
    const n = opts.n || faceNormal(pts[0], pts[1], pts[2]);
    const o = opts.origin || pts[0];
    let uA = opts.uAxis;
    let vA = opts.vAxis;
    if (!uA) uA = norm(sub(pts[1], pts[0]));
    if (!vA) vA = norm(cross(n, uA));            // right-handed: v points "up"
    let uMin = 1e9, uMax = -1e9, vMin = 1e9, vMax = -1e9;
    const proj = pts.map((p) => {
      const d = sub(p, o);
      const u = dot(d, uA), v = dot(d, vA);
      if (u < uMin) uMin = u; if (u > uMax) uMax = u;
      if (v < vMin) vMin = v; if (v > vMax) vMax = v;
      return [u, v];
    });
    const q = this.wallUV(mb, name, uMax - uMin, vMax - vMin, opts);
    const c = opts.tint || WHITE;
    const su = q.tiled ? (q.repeatU / Math.max(uMax - uMin, 1e-6)) : 0;
    const sv = q.tiled ? (q.repeatV / Math.max(vMax - vMin, 1e-6)) : 0;
    const base = mb.vertCount;
    for (let k = 0; k < pts.length; k++) {
      const p = pts[k];
      let u, v;
      if (q.tiled) {
        u = q.u0 + (proj[k][0] - uMin) * su;
        v = q.v1 - (proj[k][1] - vMin) * sv;      // +v axis is up, texture v is down
      } else {
        u = q.u0 + ((proj[k][0] - uMin) / Math.max(uMax - uMin, 1e-6)) * (q.u1 - q.u0);
        v = q.v1 - ((proj[k][1] - vMin) / Math.max(vMax - vMin, 1e-6)) * (q.v1 - q.v0);
      }
      mb.vert(p[0], p[1], p[2], n[0], n[1], n[2], c, u, v);
    }
    for (let k = 1; k < pts.length - 1; k++) mb.tri(base, base + k, base + k + 1);
    if (!opts.keepRect) mb.curRect = null;
    return base;
  }

  /**
   * A decal (window, door, garage door, rail) on a wall. `centre` is the middle
   * of the decal in world space, `right` a unit vector along the wall, `up` a
   * unit vector up it. Size defaults to the decal's natural metres × opts.scale;
   * push it opts.offset metres along the wall normal so it does not z-fight
   * (default 0.02).
   */
  decal(mb, name, centre, right, up, opts = {}) {
    const s = this.decalSize(name, opts.scale === undefined ? 1 : opts.scale);
    const w = (opts.widthM === undefined ? s.w : opts.widthM) / 2;
    const h = (opts.heightM === undefined ? s.h : opts.heightM) / 2;
    const n = opts.n || norm(cross(right, up));
    const off = opts.offset === undefined ? 0.02 : opts.offset;
    const c = [centre[0] + n[0] * off, centre[1] + n[1] * off, centre[2] + n[2] * off];
    const P = (a, b) => [c[0] + right[0] * a + up[0] * b,
      c[1] + right[1] * a + up[1] * b,
      c[2] + right[2] * a + up[2] * b];
    return this.quadTex(mb, P(-w, -h), P(w, -h), P(w, h), P(-w, h), name,
      Object.assign({ n }, opts));
  }
}

// ------------------------------------------------------------------- vec3 bits
const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0]];
const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
function norm(v) { const l = Math.hypot(v[0], v[1], v[2]) || 1; return [v[0] / l, v[1] / l, v[2] / l]; }
function faceNormal(p0, p1, p2) { return norm(cross(sub(p1, p0), sub(p2, p0))); }

// ------------------------------------------------- module-level convenience API
// These act on the atlas returned by the most recent loadMaterials() call, so
// house builders can `import { wallUV, quadTex }` and not thread the atlas
// through every function. Use the methods above if you juggle two atlases.

export function setMaterials(m) { current = m; return m; }
export function materials() {
  if (!current) throw new Error('loadMaterials() has not finished yet');
  return current;
}
export function wallUV(mb, name, widthM, heightM, opts) {
  return materials().wallUV(mb, name, widthM, heightM, opts);
}
export function quadTex(mb, p0, p1, p2, p3, name, opts) {
  return materials().quadTex(mb, p0, p1, p2, p3, name, opts);
}
export function faceTex(mb, pts, name, opts) {
  return materials().faceTex(mb, pts, name, opts);
}
export function decal(mb, name, centre, right, up, opts) {
  return materials().decal(mb, name, centre, right, up, opts);
}
export function endTex(mb) { return materials().end(mb); }
