// Rolling the map back to the summer of 2004.
//
// mapdata.js and ottawa_mapdata.js are built from today's OpenStreetMap, so
// they carry twenty-odd years of things that had not been built when this game
// is set. Two sources decide what goes:
//
//   * Statistics Canada's 2006 Census Road Network File, differenced against
//     OSM by tools/period_diff.py. Real surveyed centrelines from two years
//     after the setting: a street absent from it did not exist. The report is
//     in docs/period_2004_diff.txt and the generated keys are NEW_STREETS.
//   * A short hand-checked list of named features whose opening date is a
//     matter of public record — the Confederation Line, Zibi, Lansdowne's
//     redevelopment. Nothing goes on that list on a hunch.
//
// The rule everywhere is conservative: a street is only dropped when EVERY
// metre of it is missing from the 2006 file and it is a minor road, so that a
// generalised census centreline wandering off a real alignment can never take
// out a through route. Boulevard des Allumettières (opened 2007) is the biggest
// thing this does NOT delete — see the note on ALLUMETTIERES below.
//
// Deletion is by (name, first point) rather than by name alone, so a street
// that was widened along an older alignment keeps the part that already existed.

// [name, x, z] of the first point of every way built after 2004.
// GENERATED by tools/period_diff.py — see deletions() there.
const NEW_STREETS = [
  ["Chemin Cecil", 3383, -12477.1],
  ["Chemin Cecil", 3454.1, -12525.7],
  ["Chemin Jean-Paul Lemieux", 2955.1, -11949.4],
  ["Chemin Jean-Paul Lemieux", 3149, -12095.8],
  ["Chemin Ladyfield", 2667.8, -11320.9],
  ["Chemin Loretta", 5657.7, -9815.9],
  ["Chemin Loretta", 5840.6, -10398.7],
  ["Chemin Loretta", 5943.6, -10478],
  ["Chemin Loretta Loop", 5657.7, -9815.9],
  ["Chemin Marc-Aurèle Fortin", 2910, -11428.3],
  ["Chemin McNally", 3137.5, -13555.3],
  ["Chemin Nordik", 2668.9, -12410.4],
  ["Chemin Suzor-Coté", 3023, -11714.7],
  ["Chemin de Cabot", 2684.6, -11550.6],
  ["Chemin de Calais", 2623.4, -11540.7],
  ["Chemin de Charlotte", 2538.5, -11524],
  ["Chemin de Montpelier", 2531.1, -11618],
  ["Chemin de la Place-Charles", 5840.6, -10398.7],
  ["Chemin de la Randonnée", 3550, -12686.7],
  ["Chemin de la Randonnée", 3633, -12625],
  ["Chemin de la Traverse", 3628.3, -12394.3],
  ["Chemin du Manoir", 3137.5, -13555.3],
  ["Chemin du Relais", 3538.1, -12176.8],
  ["Impasse d'Anticosti", 6121, -12302.5],
  ["Impasse d'Anticosti", 6130, -12311.3],
  ["Impasse d'Anticosti", 6406.7, -12236.6],
  ["Impasse du Griffon", 4186.7, -940.9],
  ["Impasse du Quai", 6972.5, -14163.1],
  ["Rue Clarence", 2511.6, -1015],
  ["Rue Clarence", 2526.4, -1016.5],
  ["Rue Coleman", -2057.1, -1622.5],
  ["Rue Diane-Aldred", 756.1, -666.8],
  ["Rue Diane-Aldred", 879.8, -831.2],
  ["Rue François-Dumais", 847.6, -901.5],
  ["Rue François-Michel", 859.7, -676.3],
  ["Rue Joe-Gorman", 3018.9, -1063.3],
  ["Rue Marjorie-D.-Shackleton", 2609.5, -3816.9],
  ["Rue d'Andromède", 3136.5, -5326.6],
  ["Rue d'Outremont", 10508.1, -12069.5],
  ["Rue de Bruxelles", 2774.7, -4521.1],
  ["Rue de Bruxelles", 2777, -4447.8],
  ["Rue de Bruxelles", 2981.2, -4275.7],
  ["Rue de Bruxelles", 3179.8, -4228.3],
  ["Rue de Bruxelles", 3224.2, -4229],
  ["Rue de Bruxelles", 3291.3, -4231.3],
  ["Rue de Bruxelles", 3443.9, -4365.1],
  ["Rue de Londres", 2693.8, -4960.2],
  ["Rue de Londres", 2757.4, -4996.4],
  ["Rue de Londres", 2982.4, -4837.9],
  ["Rue de Naples", 2690.3, -4917.3],
  ["Rue de l'Abbé-Mangin", 8022.4, -11684.2],
  ["Rue de l'Embellie", 3561.6, -5157.1],
  ["Rue de l'Épée", 10306.2, -11578.1],
  ["Rue de l'Épée", 10318.8, -11588.7],
  ["Rue de la Baie", 4976.5, -13972.4],
  ["Rue de la Bourrasque", 3358.8, -5638.7],
  ["Rue de la Constellation", 4127.1, -5180.8],
  ["Rue de la Nova", 2890.3, -5336.4],
  ["Rue de la Petite-Ourse", 2599.4, -5144.3],
  ["Rue de la Vaudaire", 3223.9, -5884.7],
  ["Rue de la Vaudaire", 3263.7, -5897.4],
  ["Rue de la Vaudaire", 3351, -5846.4],
  ["Rue de la Vaudaire", 3628.7, -5850.5],
  ["Rue des Louveteaux", 2465.1, -3499.5],
  ["Rue des Louveteaux", 2563.3, -3478.2],
  ["Rue des Scouts", 2436.1, -3639.4],
  ["Rue des Scouts", 2578.9, -3548.5],
  ["Rue du Blizzard", 3423.8, -5831.1],
  ["Rue du Borée", 3343.3, -6297.7],
  ["Rue du Chinook", 3929, -6176.1],
  ["Rue du Colonial", 4788.2, -1813.5],
  ["Rue du Frimas", 3570.7, -4957.7],
  ["Rue du Glissoir", 5722.8, -12372.7],
  ["Rue du Jockey", 3014.8, -881.5],
  ["Rue du Jockey", 3124.3, -714],
  ["Rue du Jockey", 3186.1, -823.7],
  ["Rue du Jockey", 3186.1, -823.7],
  ["Rue du Joran", 3415.7, -5741.4],
  ["Rue du Shamal", 3601.2, -5962.2],
  ["Rue du Shamal", 3706.6, -5917.2],
  ["Rue du Shamal", 3759.8, -5870.9],
  ["Rue du Sirocco", 3532.3, -5897],
  ["Rue du Sulky", 3197, -754.2],
  ["Rue du Tartan", 2507.4, -1980.5],
  ["Rue du Tartan", 2532.6, -1718.7],
  ["Rue du Tartan", 2543.3, -1438.7],
  ["Rue du Tartan", 2556.7, -1452.4],
  ["Rue du Zodiaque", 2970.5, -5106.5],
  ["Rue du Zéphyr", 3590.7, -6202.3],
  ["Terrasse du Domaine", 2821.5, -13324.1],];

// Named things that plainly postdate the setting. Every one of these has a
// public opening date after 2004; nothing is here on a guess.
const GONE_POIS = [
  // Confederation Line LRT — opened September 2019. The vending machine is the
  // only trace of it in the map data, and it is a jarring one.
  'LRT tickets',
  // Zibi, on the Chaudière islands. Ground broke in 2015; in 2004 the site was
  // still the Domtar mill.
  'Zibi Block 25', 'Zibi Building 6', 'Zibi Presentation Centre',
  // Lansdowne's redevelopment, 2012-2014. The park and the stadium are old and
  // stay; the retail, the cinema and the market that came with the rebuild go.
  "Lansdowne Farmers' Market", 'Lansdowne Sports', 'Lansdowne Ticket Office',
  'Cineplex Cinemas Lansdowne and VIP', 'Lansdowne Skateboard Park',
  'Lansdowne Playground',
];

// Buildings to drop, by OSM name. Same standard of proof as GONE_POIS.
const GONE_BUILDINGS = ['Zibi Block 25', 'Zibi Building 6', 'Zibi Presentation Centre'];

// Things that existed but were called something else in 2004. The stadium at
// Lansdowne was Frank Clair Stadium until the 2014 rebuild renamed it TD Place;
// Bayview Station Road is the LRT-era name for what the 2006 census file, and
// everyone in 2004, called the Transitway.
const RENAMES = [
  ['TD Place Stadium', 'Frank Clair Stadium'],
  ['Bayview Station Road', 'Transitway'],
];

// Boulevard des Allumettières opened in 2007 and the 2006 file flags 5.9 km of
// its 20 km as new alignment — by far the largest single anachronism left in
// the map. It is deliberately NOT deleted: it is a trunk road carrying the
// east-west spine through Hull, several of its segments follow older streets it
// was built over, and cutting it risks the one thing that must not break, which
// is a continuous drivable graph from Aylmer to Ottawa. Left as a known
// inaccuracy rather than a routing bug.
const ALLUMETTIERES = 'Boulevard des Allumettières';

export function rollBackTo2004(map) {
  const key = new Set(NEW_STREETS.map(([n, x, z]) => `${n}|${x}|${z}`));
  const before = map.roads.length;
  map.roads = map.roads.filter((r) => {
    if (!r.name || !r.pts.length) return true;
    // Road geometry is emitted to one decimal place, so an exact string match
    // on the generated key is safe and costs nothing.
    return !key.has(`${r.name}|${r.pts[0][0]}|${r.pts[0][1]}`);
  });
  const roadsCut = before - map.roads.length;

  const goneP = new Set(GONE_POIS);
  const poisBefore = map.pois.length;
  map.pois = map.pois.filter((p) => !goneP.has(p.name));

  const goneB = new Set(GONE_BUILDINGS);
  const bldBefore = map.buildings.length;
  map.buildings = map.buildings.filter((b) => !b.name || !goneB.has(b.name));

  let renamed = 0;
  const ren = new Map(RENAMES);
  for (const list of [map.roads, map.buildings, map.pois, map.areas]) {
    for (const e of list) {
      const to = e.name && ren.get(e.name);
      if (to) { e.name = to; renamed++; }
    }
  }

  return {
    roadsCut,
    poisCut: poisBefore - map.pois.length,
    buildingsCut: bldBefore - map.buildings.length,
    renamed,
    keptKnownAnachronism: ALLUMETTIERES,
  };
}
