// Bake the hero footprints into a standalone module for the landmark lab.
//
//   node tools/build_hero_rings.mjs
//
// src/game/ottawa_lab.html exists so a roofline can be iterated on without the
// four-second world bake; importing ottawa.js to get the rings would put 21 MB
// of map modules back in front of it, which defeats the point. This writes the
// eleven rings the six landmarks actually use — about 20 KB.
//
// tools/smoke_ottawa.mjs checks the baked copy still matches the live map, so
// this cannot silently drift out of date.
import { writeFileSync } from 'node:fs';
import '../src/game/ottawa.js';
import { heroRings, HERO } from '../src/game/ottawa_landmarks.js';

const rings = heroRings();
const body = Object.entries(rings)
  .map(([id, r]) => ` ${id}: [${r.map((p) => `[${p[0]},${p[1]}]`).join(',')}]`)
  .join(',\n');
const text = `// GENERATED by tools/build_hero_rings.mjs — do not edit by hand.
// The real OpenStreetMap footprints (ODbL) of the six Ottawa hero landmarks,
// in the mapdata frame, so src/game/ottawa_lab.html can draw them without
// loading the whole map. The game itself never reads this: it takes the rings
// off MAP directly in clearHeroFootprints().
export const HERO_RINGS = {
${body},
};
`;
writeFileSync(new URL('../src/game/ottawa_hero_rings.js', import.meta.url), text);
console.log(`${Object.keys(rings).length} rings for ${HERO.length} landmarks, ${(text.length / 1024).toFixed(1)} KB`);
