#!/usr/bin/env python3
"""Per-street summary of data/houses.json -> docs/HOUSES-REPORT.md.

The point is the "yeah, that's my street" test: someone who grew up in Aylmer
should be able to read a line and say whether it is right, without opening the
game.  So each line is one street: how many houses, what years, how tall, how
they are attached, roofs, garages, and where the numbers came from.

    python3 tools/houses_report.py
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_map as bm

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'HOUSES-REPORT.md')

# The addresses in README.md that will actually get checked.
LANDMARKS = [
    ('Chemin Fraser', '299'), ('Rue Denise-Friend', '75'),
    ('Rue Bancroft', '27'), ('Chemin Vanier', '20'),
    ('Avenue Frank-Robinson', '129'),
]


def pct(n, d):
    return 0 if not d else round(100 * n / d)


def dominant(counter, n=2):
    return ', '.join(f'{k} {pct(v, sum(counter.values()))}%'
                     for k, v in counter.most_common(n))


def storey_str(vals):
    lo, hi = min(vals), max(vals)
    f = lambda v: str(int(v)) if v == int(v) else str(v)
    return f(lo) if lo == hi else f'{f(lo)}–{f(hi)}'


def main():
    with open(os.path.join(ROOT, 'data', 'houses.json')) as f:
        houses = json.load(f)
    streets = collections.defaultdict(list)
    byaddr = {}
    unaddressed = []
    for w in bm.load('buildings.json'):
        k = str(w['id'])
        h = houses.get(k)
        if not h:
            continue
        t = w.get('tags', {})
        st = t.get('addr:street')
        if st:
            streets[st].append(h)
            byaddr[(st, (t.get('addr:housenumber') or '').strip())] = h
        else:
            unaddressed.append(h)

    lines = []
    lines.append('# Aylmer houses — per-street report')
    lines.append('')
    lines.append('Generated by `tools/houses_report.py` from `data/houses.json`. '
                 'Do not edit by hand.')
    lines.append('')
    lines.append('Sources: Québec **rôle d\'évaluation foncière** 2026 for Gatineau '
                 '(MAMH, CC-BY 4.0) for year built, storeys, construction type and '
                 'physical link; **MRNF 2020 LiDAR** (single-return hard surfaces over '
                 'the class-2 ground model) for eave and ridge height, roof form '
                 'and ridge direction; footprint shape '
                 'and the neighbourhood priors in `tools/houses_priors.py` for the '
                 'rest. See `docs/HOUSES.md`.')
    lines.append('')

    tot = len(houses)
    r = sum(1 for h in houses.values() if h['src']['roll'])
    l = sum(1 for h in houses.values() if h['src']['lidar'])
    so = sum(1 for h in houses.values()
             if not h['src']['roll'] and not h['src']['lidar'])
    lines.append(f'**{tot} houses.** Assessment roll {r} ({pct(r, tot)}%) · '
                 f'LiDAR {l} ({pct(l, tot)}%) · shape + priors only {so} '
                 f'({pct(so, tot)}%).')
    lines.append('')

    ec = collections.Counter(h['era'] for h in houses.values())
    lines.append('| era | houses |')
    lines.append('|---|---:|')
    for k in ('old', 'midcentury', 'cottage', 'suburban', 'modern'):
        lines.append(f'| {k} | {ec.get(k, 0)} |')
    lines.append('')

    lines.append('## The addresses that will get checked')
    lines.append('')
    for st, hn in LANDMARKS:
        h = byaddr.get((st, hn))
        if not h:
            lines.append(f'- **{hn} {st}** — not in the clip')
            continue
        y = h['year'] or '?'
        rh = f", ridge {h['ridgeHeight']} m" if h['ridgeHeight'] else ''
        lines.append(
            f"- **{hn} {st}** — {y}, {h['era']}, {storey_str([h['storeys']])} storey, "
            f"{h['link']}, {h['roof']} roof, eave {h['height']} m{rh}, "
            f"garage {h['garage']}, porch {'yes' if h['porch'] else 'no'} "
            f"(roll {'y' if h['src']['roll'] else 'n'}, "
            f"lidar {'y' if h['src']['lidar'] else 'n'})")
    lines.append('')

    lines.append('## Streets')
    lines.append('')
    lines.append('Year range is the 10th–90th percentile, so a single 1830 '
                 'survivor on a 1970s street does not swamp the line.')
    lines.append('')

    for st in sorted(streets, key=lambda s: (-len(streets[s]), s)):
        hs = streets[st]
        if len(hs) < 3:
            continue
        ys = sorted(h['year'] for h in hs if h['year'])
        if ys:
            lo = ys[max(0, int(len(ys) * 0.10))]
            hi = ys[min(len(ys) - 1, int(len(ys) * 0.90))]
            med = ys[len(ys) // 2]
            yr = f'{lo}–{hi}' if lo != hi else f'{lo}'
            yr += f' (median {med})'
        else:
            yr = 'year unknown'
        era = collections.Counter(h['era'] for h in hs)
        link = collections.Counter(h['link'] for h in hs)
        roof = collections.Counter(h['roof'] for h in hs)
        gar = collections.Counter(h['garage'] for h in hs)
        att = pct(gar['attached'], len(hs))
        nroll = pct(sum(1 for h in hs if h['src']['roll']), len(hs))
        nlid = pct(sum(1 for h in hs if h['src']['lidar']), len(hs))
        lines.append(
            f"**{st}**: {len(hs)} houses, {yr}, "
            f"{storey_str([h['storeys'] for h in hs])} storeys, "
            f"{dominant(era, 2)}; {dominant(link, 2)}; {dominant(roof, 2)}; "
            f"{att}% attached garage"
            + (f", {pct(gar['detached'], len(hs))}% detached garage"
               if gar['detached'] else '')
            + (f", {pct(gar['carport'], len(hs))}% carport" if gar['carport'] else '')
            + f". _roll {nroll}%, lidar {nlid}%_")
        lines.append('')

    small = [s for s in streets if len(streets[s]) < 3]
    if small:
        lines.append(f'_{len(small)} streets with fewer than three houses in the '
                     f'clip are omitted; {len(unaddressed)} footprints carry no '
                     f'address at all._')
        lines.append('')

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {os.path.relpath(OUT, ROOT)} '
          f'({len([s for s in streets if len(streets[s]) >= 3])} streets)',
          file=sys.stderr)


if __name__ == '__main__':
    main()
