// G1 — mission timers have never been driven by a real player, and nobody in
// this repo can drive. So instead of guessing, measure: route every mission
// stage over the real road graph with the same Nav the GPS uses, and print how
// fast the current timer is actually asking you to go.
//
//   node tools/timers.mjs          -> writes tools/timers.md
//   node tools/timers.mjs --print  -> stdout
//
// This changes no timers. It is a table for a human to tune from.

import { MAP } from '../src/game/mapdata.js';
import { PLACES, resolvePlaces } from '../src/game/places.js';
import { MISSIONS } from '../src/game/missions.js';
import { Nav, routeLength } from '../src/game/nav.js';
import { CARS } from '../src/game/cars.js';

// world.js's nearestRoad, minus the WebGL: closest point on any non-service
// road. resolvePlaces only ever asks for this one method.
function stubWorld() {
  return {
    nearestRoad(x, z) {
      let best = Infinity, bx = x, bz = z, byaw = 0, bname = '';
      for (const r of MAP.roads) {
        if (r.cls === 'service') continue;
        const p = r.pts;
        for (let i = 0; i + 1 < p.length; i++) {
          const ax = p[i][0], az = p[i][1];
          const dx = p[i + 1][0] - ax, dz = p[i + 1][1] - az;
          const l2 = dx * dx + dz * dz;
          let t = l2 > 1e-9 ? ((x - ax) * dx + (z - az) * dz) / l2 : 0;
          t = t < 0 ? 0 : t > 1 ? 1 : t;
          const px = ax + t * dx, pz = az + t * dz;
          const d2 = (px - x) ** 2 + (pz - z) ** 2;
          if (d2 < best) { best = d2; bx = px; bz = pz; byaw = Math.atan2(dx, dz); bname = r.name || ''; }
        }
      }
      return { x: bx, z: bz, yaw: byaw, name: bname, dist: Math.sqrt(best) };
    },
  };
}

const resolveAt = (at) => (typeof at === 'string' ? PLACES[at] : at);

// Walk one mission's stages, routing each leg from where the last one ended.
export function measure(def, nav, ctx) {
  const stages = def.build(ctx);
  const giver = PLACES[def.giver];
  let x = giver.x, z = giver.z;
  const out = [];
  for (let i = 0; i < stages.length; i++) {
    const st = stages[i];
    const p = resolveAt(st.at);
    const path = nav.route(x, z, p.x, p.z);
    const metres = path ? routeLength(path, x, z) : NaN;
    out.push({
      i,
      text: st.text,
      metres,
      time: st.time ?? null,
      maxSpeed: st.maxSpeed ?? null,
      radius: st.radius ?? 14,
      routed: !!path,
    });
    x = p.x; z = p.z;
  }
  return { def, stages: out };
}

const kmh = (m, s) => (s ? (m / s) * 3.6 : null);
const f1 = (v) => (v == null || !isFinite(v) ? '—' : v.toFixed(1));
const f0 = (v) => (v == null || !isFinite(v) ? '—' : Math.round(v).toLocaleString('en-CA'));

export function buildTimersTable() {
  resolvePlaces(stubWorld());
  const nav = new Nav();

  // Only "gang" changes shape with the car (the Ranger's bench seats two), so
  // measure it for both a 2-seater and a 3-seater and leave the rest alone.
  const ranger = CARS.find((c) => c.id === 'ranger');
  const saturn = CARS.find((c) => c.id === 'saturn');
  const ctxOf = (c) => ({ carId: c.id, carName: c.name, seats: c.seats });

  const lines = [];
  lines.push('# Mission timers vs. actual route length');
  lines.push('');
  lines.push('Generated by `node tools/timers.mjs`. **No timers were changed by this file.**');
  lines.push('');
  lines.push('`route m` is the Dijkstra route over the real road graph, from where the');
  lines.push('previous stage ended to this stage\'s target — the same path the GPS line');
  lines.push('draws. `implied km/h` is what the current timer demands as a door-to-door');
  lines.push('average, stops, traffic and the stage radius included. `@40 km/h` is what the');
  lines.push('timer would be at a relaxed 40 km/h average, as a starting point for tuning.');
  lines.push('');
  lines.push('Top speeds for scale: ' + CARS.map((c) => `${c.name.split(' ').slice(-1)[0]} ${Math.round(c.topSpeed * 3.6)}`).join(' · ') + ' km/h.');
  lines.push('');
  lines.push('| mission | stage | target | route m | timer s | implied km/h | @40 km/h |');
  lines.push('|---|---|---|---:|---:|---:|---:|');

  const rows = [];
  for (const def of MISSIONS) {
    const m = measure(def, nav, ctxOf(saturn));
    let total = 0, timed = 0, allTimed = true;
    for (const st of m.stages) {
      total += isFinite(st.metres) ? st.metres : 0;
      if (st.time) timed += st.time; else allTimed = false;
      const v = kmh(st.metres, st.time);
      rows.push(`| ${def.id} | ${st.i + 1}/${m.stages.length} | ${st.text} | ${f0(st.metres)} | ` +
        `${st.time ?? '—'} | ${f1(v)} | ${st.time ? f0(st.metres / (40 / 3.6)) : '—'} |` +
        (st.maxSpeed ? ` <!-- max ${st.maxSpeed} km/h -->` : ''));
    }
    // Only meaningful when every stage is on a clock: an untimed stage is
    // driven at leisure, so mixing it into the average is nonsense.
    rows.push(`| **${def.id}** | **total** | ${m.stages.length} stages | **${f0(total)}** | ` +
      `**${timed || '—'}** | ${allTimed ? f1(kmh(total, timed)) : '—'} | ${f0(total / (40 / 3.6))} |`);
  }
  lines.push(...rows);
  lines.push('');

  // The Ranger re-plans "gang" into two trips; that is a different distance.
  const gang = MISSIONS.find((d) => d.id === 'gang');
  if (gang) {
    const r = measure(gang, nav, ctxOf(ranger));
    lines.push('## `gang` in the Ranger (bench seats two, so it is two trips)');
    lines.push('');
    lines.push('| stage | target | route m | timer s | implied km/h |');
    lines.push('|---|---|---:|---:|---:|');
    let total = 0;
    for (const st of r.stages) {
      total += isFinite(st.metres) ? st.metres : 0;
      lines.push(`| ${st.i + 1}/${r.stages.length} | ${st.text} | ${f0(st.metres)} | ${st.time ?? '—'} | ${f1(kmh(st.metres, st.time))} |`);
    }
    lines.push(`| **total** | ${r.stages.length} stages | **${f0(total)}** | — | — |`);
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- Stages with no `time` inherit the previous stage\'s clock (`applyStage` only');
  lines.push('  resets `timeLeft` when the stage declares one), so a `—` row is untimed.');
  lines.push('- A **total** row only shows an implied average when every stage is timed.');
  lines.push('- `tour` is one clock per checkpoint and `dep` is the other tight one — those');
  lines.push('  are the rows to look at first.');
  lines.push('- Route length is a lower bound on what you actually drive: no U-turns, no');
  lines.push('  overshooting the stage radius, no waiting for traffic.');
  lines.push('- `nearestRoad` here is a stand-in for `world.js`\'s (same rule: nearest point');
  lines.push('  on a non-service road), so a place may snap a metre or two differently.');
  lines.push('');
  return lines.join('\n');
}

// CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const md = buildTimersTable();
  if (process.argv.includes('--print')) {
    process.stdout.write(md);
  } else {
    const { writeFileSync } = await import('node:fs');
    const { fileURLToPath } = await import('node:url');
    const { dirname, join } = await import('node:path');
    const out = join(dirname(fileURLToPath(import.meta.url)), 'timers.md');
    writeFileSync(out, md);
    console.log('wrote ' + out);
  }
}
